spring:
    data:
        mongodb:
            uri: ${MONGODB_URI:mongodb+srv://vsolabswork:Vs0labs25@cluster0.o5mrlm7.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
            database: ${MONGODB_DATABASE:daddyJohn}
            auto-index-creation: true

    # File upload configuration
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
            enabled: true

logging:
    level:
        com.vso.DaddyJohn: ${LOG_LEVEL:INFO}
        com.vso.DaddyJohn.Service.MessageService: DEBUG
        org.springframework.web.client.RestTemplate: DEBUG
        org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
        org.springframework.web.cors: ${CORS_LOG_LEVEL:INFO}

server:
    port: ${PORT:8080}

app:
    jwt:
        secret: ${JWT_SECRET:YourDefaultSecretValueIfNotProvided}
        expiration-ms: ${JWT_EXPIRATION_MS:3600000}

    # File storage configuration
    file:
        upload-dir: ${UPLOAD_DIR:uploads}
        base-url: ${FILE_BASE_URL:http://localhost:8080/files}

services:
    chatbot:
        django-url: ${DJANGO_API_URL:https://renderdeploy-1-gpz1.onrender.com/chat}